### ISSUE TITLE
Exception not caught when asttokens raise a TokenError

### ISSUE THREAD

**Issue by aroberge** [alexmojaki/stack_data#16]
When using a malformed jinja2 template, some uncaught errors bubble up.

See https://github.com/friendly-traceback/friendly-traceback/issues/73 for details.

Perhaps this will also require a change to executing (to handle KeyError).

**Comment by alexmojaki** [comment]
Should be fixed by https://github.com/alexmojaki/stack_data/commit/3c3f77c7975228863c92a5f78f14bb22c7df97c9, try updating

**Comment by aroberge** [comment]
Thanks!
