### ISSUE TITLE
Bug with IPython 8.1.0

### ISSUE THREAD

**Issue by aroberge** [alexmojaki/stack_data#23]
With the latest release of IPython (8.1.0), in at least one instance stack_data does not identify a node.
Here are two screen captures illustrating the different behaviour. First, the correct identification done with 8.0.1
![image](https://user-images.githubusercontent.com/629698/155896484-f26b467b-54e2-491b-8122-a3e888a4c7d9.png)

Next, with 8.1.0, the problematic node is not highlighgted.

![image](https://user-images.githubusercontent.com/629698/155897452-d5499229-43db-445e-ba50-4024a7551e61.png)

I have documented this as well in https://github.com/friendly-traceback/friendly/issues/28.

For some other IndexError cases, there does not seem to be any problem in identifying the problematic node.
![image](https://user-images.githubusercontent.com/629698/155896562-fa5f2b3f-d92e-4310-8879-30e1143684de.png)

Note that I did not file an issue with IPython itself.

**Comment by aroberge** [comment]
Some information should be provided when stack_data fails; see https://github.com/friendly-traceback/friendly-traceback/issues/124

**Comment by alexmojaki** [comment]
The first two images are the same

**Comment by aroberge** [comment]
Sorry about that :(
![image](https://user-images.githubusercontent.com/629698/155897431-70f91094-e9d9-4bec-a5c9-6eea78e94677.png)

**Comment by alexmojaki** [comment]
Thanks for the report. This was a lot like when they changed the filenames of cells, but now it was the change of the code name from `<module>` to `<cell line: 1>`. Upgrade `executing` and try again.

**Comment by aroberge** [comment]
It works perfectly!  Thank you for the quick fix.
