### ISSUE TITLE
How to restrict interesting expressions

### ISSUE THREAD

**Issue by spacemanspiff2007** [alexmojaki/stack_data#27]
Fist of all thank you for your stack_data library. It's really helpful and I am currently in the process of migrating an application to it.
Whily trying to format some nice tracebacks I noticed that sometimes the returned variables add up quickly.

This code

```python
    assert isinstance(topic, str), type(topic)
    assert isinstance(qos, int) or qos is None, type(qos)
    assert isinstance(retain, bool) or retain is None, type(retain)
```

generates
```
type(qos) = <class 'NoneType'>
type(retain) = <class 'NoneType'>
type(topic) = <class 'str'>
qos = None
qos is None = True
retain = None
retain is None = True
topic = 'my_topic'
```

Is there an elegant way to distinguish the returned variables?
E.g. this variable is an expression and this is an actual variable?
Then it would be easier to clean them in post processing.

**Comment by alexmojaki** [comment]
Are you working directly with `FrameInfo.variables`, or are you using a `Formatter`?

`Variable.nodes[0]` (all the nodes are equivalent, just in different places) is an AST node whose type you can check. If it's an `ast.Name`, it's an actual variable. You may also want to keep `ast.Attribute` and perhaps `ast.Subscript`.

**Comment by spacemanspiff2007** [comment]
Thank you for your prompt reply. I am using `FrameInfo.variables`.
I'll take a look at your suggestion.
