### ISSUE TITLE
Tests are failing with Pygments 2.12.0

### ISSUE THREAD

**Issue by frenzymadness** [alexmojaki/stack_data#28]
In Fedora, we've discovered that two tests of stack_data are not compatible with the latest Pygments. I did a bisection of the commits between Pygments' releases and the problem is caused by this change: https://github.com/pygments/pygments/commit/1458c6669bbc9121eb80b08a7112d81899da7344 

I'll try to open a PR soon.

**Comment by frenzymadness** [comment]
So the first problem is that the colors are different which makes `test_executing_style_defs` fail. I'd use a regex and make the test parametrized to allow both possible colors in the test and therefore it should be compatible with both Pygments.

The second one is caused by a lot of differences in output in `test_pygments_example` which would require to have two different outputs for the new/old version of Pygments. Is this acceptable for you to have two 120 lines long strings for that? I can also refresh the string and skip the test for the old Pygments.

Let me know what you prefer.

**Comment by alexmojaki** [comment]
Hi, thanks for this. I think it's fine for the tests to only support the newest version.
