### ISSUE TITLE
No line numbers when executing code directly

### ISSUE THREAD

**Issue by spacemanspiff2007** [alexmojaki/stack_data#33]
If code is run with ``exec`` or as a subprocess with ``python -c`` the line numbers are missing in the ``FrameInfo``.

```python
code = """
from stack_data import FrameInfo, Options

def format_exception(e: Exception):
    for frame in tuple(FrameInfo.stack_data(e.__traceback__)):
        print(frame.lines[-1].lineno)

try:
    1/0
except Exception as e:
    format_exception(e)
"""
exec(code)
```

Access of ``frame.lines[-1]`` fails:
```
Traceback (most recent call last):
  File "<string>", line 9, in <module>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python\__test_error_format.py", line 13, in <module>
    exec(code)
  File "<string>", line 11, in <module>
  File "<string>", line 6, in format_exception
IndexError: list index out of range
```

The default traceback contains the line numbers so I'm guessing there is another mechanism that's used to get them.

**Comment by alexmojaki** [comment]
You can just use `frame.lineno`. I see that's missing from the docstring, sorry.

`.lines` is primarily about getting source code, so it's empty when the source code isn't available. See https://github.com/alexmojaki/snoop/issues/28#issuecomment-738996384 for how to make it available.

**Comment by spacemanspiff2007** [comment]
Thank you for your quick reply!
Is ``frame.lineno`` this highest number in the  frame or the line of the exception?

I am actually using this to run the code since I need a new process so it doesn't pollute the existing interpreter:
```
import subprocess, sys

r = subprocess.run([sys.executable, '-c', code], capture_output=True)
for line in r.stderr.decode().splitlines():
    print(line)
```
Is it there somehow possible, too?

**Comment by alexmojaki** [comment]
It's the line of the exception, the same line number you see in the regular traceback.

If you really need to use a new process, I suggest writing the code to a file and running that file instead of using `-c`.

If a new process is not critical for security or anything, check out https://github.com/alexmojaki/python_runner. Each code run will be in a fresh module.

**Comment by spacemanspiff2007** [comment]
I have multiple modules that internally store states. I am running the code in a fresh interpreter to prevent the leakage of states between executions. From the docs it's currently unclear if ``python_runner`` provides that kind of desired isolation - if yes this sounds like a very good solution.

**Comment by alexmojaki** [comment]
It's not that kind of isolation.

**Comment by spacemanspiff2007** [comment]
Thank you for your help and hints!
