### ISSUE TITLE
temporary values

### ISSUE THREAD

**Issue by hrbigelow** [alexmojaki/stack_data#43]
Hi Alex,

I wondered what would be the best way to produce the following (something like) traceback message:

```python
def add(a, b):
    return a + b

def fadd(a, b):
    return 'fake'

def test3():
    return add(add(2, 4), fadd(3, 5))

test3()
```

and traceback message something like this:

```python
return add(add(2, 4), fadd(3 ,5))
           ^^^^^^^^   ^^^^^^^^^^
Values:
=> add(2, 4) = 6
=> fadd(3, 5) = 'fake'
```

When perusing the `FrameInfo` object associated with `test3` (that is, such that `fi.executing.code_qualname() = 'test3'`, the `variables` member was empty.  Is there any place where the temporary values of `add(2, 4)` and `fadd(3, 5)` would be stored in the `FrameInfo` object, or would that have to be reconstructed from the lower frame?

Thanks very much!

Henry

**Comment by alexmojaki** [comment]
No, Python doesn't keep those anywhere. You'd need to record them beforehand. You might be interested in https://github.com/alexmojaki/birdseye/ or https://github.com/alexmojaki/snoop#ppdeep-for-tracing-subexpressions

**Comment by hrbigelow** [comment]
Ahh I see, thanks for the prompt reply (and for stack_data!)
