### ISSUE TITLE
Conflicting Installation Instructions on PyPI.org

### ISSUE THREAD

**Issue by mitsuj** [alexmojaki/stack_data#55]
There are **two different installation command** for this package on [PyPI]
(https://pypi.org/project/stack-data/)

1. pip install stack-data

![image](https://github.com/alexmojaki/stack_data/assets/72346691/580dddf3-356d-4457-af7b-4f281d595201)

2. pip install stack_data

![image](https://github.com/alexmojaki/stack_data/assets/72346691/e5065716-0dbb-4b8d-b3c9-2c6a7c11c61b)

This could be a security issue since "stack-data" and "stack_data" are different names.

**Comment by alexmojaki** [comment]
No, pip/pypi treat `-` and `_` as interchangeable. Thanks for your concern though!
